# Zeabur 配置文件
name: trading-dashboard

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env:
      - DATABASE_URL
      - OANDA_API_KEY
      - OANDA_ACCOUNT_ID
      - OANDA_API_URL
    ports:
      - ${PORT}:${PORT}
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env:
      - NEXT_PUBLIC_API_URL
    ports:
      - 3000:3000
    depends_on:
      - backend

